name: touch_to_expand_container
description: "A container that maintains a single/continuous child instance while expanded, which Overlay widget in Flutter doesn't and cannot. All UX-oriented customizables are API-supported."
version: 0.1.0
homepage: https://github.com/chleosl/touch_to_expand_container
repository: https://github.com/chleosl/touch_to_expand_container

documentation: https://pub.dev/documentation/touch_to_expand_container/latest/
issue_tracker: https://github.com/chleosl/touch_to_expand_container/issues

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"
# minimum requirement version not discovered or designated yet

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
 - ui
 - overlay
 - single-instance
 - preview
 - expand
 - ux-design
 - ux-oriented
 - transform
 - singleton
 - overlay-preview
 - hunter-killer

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

screenshots:
  - description: 'Interactive Demo app 1'
    path: images/demo1.webp
  - description: 'Interactive Demo app 2'
    path: imgaes/demo2.webp
  - description: 'Interactive Demo app 3'
    path: imgaes/demo3.webp